#docker-compose -f docker-compose-mysql2.yml up -d
version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: db002
    hostname: db002
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db002/data:/var/lib/mysql
      - ./db002/log:/var/log/mysql
      - ./db002/conf:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    restart: unless-stopped