#docker-compose -f docker-compose-redis.yml up -d
#docker-compose -f docker-compose-redis.yml down
version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]  # AOF(Append Only File) 옵션 활성화

volumes:
  redis_data:  # Redis 데이터 볼륨을 생성합니다.