version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql-container
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - hh99:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  hh99: