#docker-compose -f docker-compose-mysql.yml up -d
version: '3'

services:
  db001:
    image: mysql:8.0.33
    container_name: db001
    hostname: db001
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # Where our data will be persisted
    volumes:
      - master:/var/lib/mysql
      - master:/var/lib/mysql-files
      - ./db001/conf:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    networks:
      - net-mysql

  db002:
    image: mysql:8.0.33
    container_name: db002
    hostname: db002
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # Where our data will be persisted
    volumes:
      - slave:/var/lib/mysql
      - slave:/var/lib/mysql-files
      - ./db002/conf:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    restart: unless-stopped
    networks:
      - net-mysql

# Names our volume
volumes:
  master:
  slave:

networks:
  net-mysql:
    driver: bridge