name: billing_project

on:
  push:
    branches: [ "main_discovery" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'  # 서브모듈을 포함하여 체크아웃

      - name: Check directory structure
        run: |
          pwd
          ls -la

      - name: List contents of discovery_module
        run: ls -la discovery_module
      - name: List contents of discovery_module/src/main
        run: ls -la discovery_module/src/main

      - name: Create resources directory if missing
        run: |
          mkdir -p discovery_module/src/main/resources

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make application.properties
        run: |
          cd /home/runner/work/billingProject/billingProject/discovery_module/src/main/resources
          touch application.properties
          echo "${{ secrets.DISCOVERY_MODULE_PROPERTIES }}" > application.properties
        shell: bash

      - name: Build and push Docker images
        run: |
          ./gradlew bootJar -p discovery_module
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./Dockerfile_Discovery -t ${{ secrets.DOCKER_USERNAME }}/discovery_module .
          docker push ${{ secrets.DOCKER_USERNAME }}/discovery_module

      - name: Execute Docker Compose
        run: |
          docker-compose down
          docker rmi ${{ secrets.DOCKER_USERNAME }}/discovery_module
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/discovery_module
          ssh -i ${{ secrets.KEY }} ubuntu@${{ secrets.DISCOVERY_MODULE_HOST }} 'bash -s' << EOF
          docker-compose -f ./docker/docker-compose-discovery_module.yml up -d
          docker image prune -f
          EOF
