name: billing_project

on:
  push:
    branches: [ "main_discovery" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Display working directory
        run: pwd

      - name: List directory contents
        run: ls -la

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make application.properties
        run: |
          cd ./discovery_module/src/main/resources
          touch application.properties
          echo "${{ secrets.DISCOVERY_MODULE_PROPERTIES }}" > application.properties
        shell: bash

      - name: Build and push Docker images
        run: |
          cd discovery_module
          ./gradlew bootJar
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./Dockerfile_Discovery -t ${{ secrets.DOCKER_USERNAME }}/discovery_module .
          docker push ${{ secrets.DOCKER_USERNAME }}/discovery_module

      - name: Execute Docker Compose
        run: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/discovery_module
          ssh -i ${{ secrets.KEY }} ubuntu@${{ secrets.DISCOVERY_MODULE_HOST }} 'bash -s' << EOF
            docker-compose -f ./docker/docker-compose-discovery_module.yml up -d
            docker image prune -f
          EOF
