name: billing_project

on:
  push:
    branches: [ "main_watch_history" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Create resources directory if missing
        run: |
          mkdir -p watch_history_module/src/main/resources

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make application.properties
        run: |
          cd /home/runner/work/billingProject/billingProject/watch_history_module/src/main/resources
          touch application.properties
          echo "${{ secrets.WATCH_MODULE_PROPERTIES }}" > application.properties
        shell: bash

      - name: Build and push Docker images
        run: |
          ./gradlew bootJar -p watch_history_module
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./Dockerfile_WatchHistory -t ${{ secrets.DOCKER_USERNAME }}/watch_history_module .
          docker push ${{ secrets.DOCKER_USERNAME }}/watch_history_module

      - name: Execute Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WATCH_MODULE_HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/watch_history_module
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/watch_history_module
            docker-compose up -d
            docker image prune -f